import { IMenuToken, IThemeWithoutComponents } from '../../interfaces';

export default function createMenuToken({
  spacing,
  size,
  colors,
  typography,
}: IThemeWithoutComponents): IMenuToken {
  const {
    spec: { fontSize, fontWeight },
  } = typography;
  const { spec: colorsSpec, pattern: colorsPattern } = colors;
  const { spec: spacingSpec } = spacing;
  return {
    wrapper: {
      inlineCollapsedWidth: fontSize.s3 + spacingSpec.s4 * 4,
      borderRadius: size.spec.borderRadius.s2,
      background: colorsPattern.background.higher,
    },
    item: {
      indent: spacingSpec.s7,
      indentWithIcon: 32,
      marginHorizontal: spacingSpec.s4,
      marginVertical: spacingSpec.s2,
      paddingHorizontal: spacingSpec.s4,
      verticalPaddingHorizontal: spacingSpec.s5,
      horizontalPaddingHorizontal: spacingSpec.s6,
      background: {
        normal: 'transparent',
        hover: colorsSpec.neutral10.normal,
        clicked: colorsSpec.neutral10.normal,
        selected: colorsSpec.lightBrand1,
        selectedHover: colorsSpec.lightBrand2,
        selectedClicked: colorsSpec.lightBrand1,
        disabled: 'transparent',
      },
      color: {
        normal: colorsSpec.neutral2.normal,
        hover: colorsSpec.neutral2.normal,
        clicked: colorsSpec.neutral2.normal,
        selected: colorsSpec.brand,
        selectedHover: colorsSpec.brand,
        selectedClicked: colorsSpec.brand,
        disabled: colorsSpec.neutral6.normal,
      },
      fontWeight: {
        normal: fontWeight.regular,
        selected: fontWeight.semibold,
        disabled: fontWeight.regular,
      },
      horizontalBackground: {
        normal: 'transparent',
        hover: colorsSpec.light,
        clicked: colorsSpec.light,
        selected: colorsSpec.light,
        selectedHover: colorsSpec.light,
        selectedClicked: colorsSpec.light,
        disabled: 'transparent',
      },
      horizontalColor: {
        normal: colorsSpec.neutral2.normal,
        hover: colorsSpec.brand,
        clicked: colorsSpec.brand,
        selected: colorsSpec.brand,
        selectedHover: colorsSpec.brand,
        selectedClicked: colorsSpec.brand,
        disabled: colorsSpec.neutral6.normal,
      },
    },
    tooltip: {
      offset: spacingSpec.s3,
      size: 'l',
    },
    background: 'transparent',
    height: 32,
    verticalHeight: {
      s: 32,
      m: 32,
      l: 40,
      xl: 40,
    },
    verticalBorderRadius: size.spec.borderRadius.s1,
    fontLevel: 's2',
    verticalFontLevel: {
      s: 's1',
      m: 's1',
      l: 's2',
      xl: 's2',
    },
    iconMarginRight: spacingSpec.s4,
    iconColor: colorsPattern.icon.normal,
    highlightIconColor: colorsPattern.text.highlight,
    verticalIconFontLevel: {
      s: 's2',
      m: 's2',
      l: 's3',
      xl: 's3',
    },
    iconFontLevel: 's3',
    group: {
      indent: spacingSpec.s7,
      indentWithIcon: 24,
      fontLevel: 's1',
      height: 34,
      verticalHeight: 26,
      paddingHorizontal: spacingSpec.s6,
      paddingTop: spacingSpec.s6,
      itemPaddingInGroup: spacingSpec.s6 - spacingSpec.s4,
      verticalpaddingTop: spacingSpec.s4,
      background: 'transparent',
      color: colorsPattern.text.assistant,
    },
    subMenu: {
      indent: spacingSpec.s7,
      indentWithIcon: 24,
      offset: 6,
      offsetHasScrollBar: 18,
      verticalMinWidth: 124,
      verticalPaddingVertical: spacingSpec.s2,
      preventOverflowPadding: 100,
      scrollBarPadding: spacingSpec.s2,
      background: {
        normal: 'transparent',
        hover: colorsSpec.neutral10.normal,
        clicked: colorsSpec.neutral10.normal,
        selected: colorsSpec.lightBrand1,
        selectedHover: colorsSpec.lightBrand2,
        selectedClicked: colorsSpec.lightBrand1,
        disabled: 'transparent',
      },
      color: {
        normal: colorsSpec.neutral2.normal,
        hover: colorsSpec.neutral2.normal,
        clicked: colorsSpec.neutral2.normal,
        selected: colorsSpec.brand,
        selectedHover: colorsSpec.brand,
        selectedClicked: colorsSpec.brand,
        disabled: colorsSpec.neutral6.normal,
      },
      fontWeight: {
        normal: fontWeight.regular,
        selected: fontWeight.semibold,
        disabled: fontWeight.regular,
      },
      horizontalBackground: {
        normal: 'transparent',
        hover: colorsSpec.light,
        clicked: colorsSpec.light,
        selected: colorsSpec.light,
        selectedHover: colorsSpec.light,
        selectedClicked: colorsSpec.light,
        disabled: 'transparent',
      },
      horizontalColor: {
        normal: colorsSpec.neutral2.normal,
        hover: colorsSpec.brand,
        clicked: colorsSpec.brand,
        selected: colorsSpec.brand,
        selectedHover: colorsSpec.brand,
        selectedClicked: colorsSpec.brand,
        disabled: colorsSpec.neutral6.normal,
      },
    },
    divider: {
      paddingHorizontal: spacingSpec.s6,
      paddingVertical: 5.5,
    },
  };
}
