import { IBreakpoints } from './breakpoints';
import { IColors } from './colors';
import { IAlertToken } from './components/alertToken';
import { IBadgeToken } from './components/badgeToken';
import { IBaseMenuToken } from './components/baseMenuToken';
import { IBreadcrumbsToken } from './components/breadcrumbsToken';
import { IButtonToken } from './components/buttonToken';
import { ICalendarToken } from './components/calendarToken';
import { ICardToken } from './components/cardToken';
import { ICarouselToken } from './components/carouselToken';
import { ICascaderToken } from './components/cascaderToken';
import { ICheckboxToken } from './components/checkboxToken';
import { IDatePickerToken } from './components/datePickerToken';
import { IDialogToken } from './components/dialogToken';
import { IDropdownToken } from './components/dropdownToken';
import { IFormToken } from './components/formToken';
import { IGuideToken } from './components/guideToken';
import { IImgCropperToken } from './components/imgCropperToken';
import { IImgPreviewToken } from './components/imgPreviewToken';
import { IImgToken } from './components/imgToken';
import { IInputNumberToken } from './components/inputNumberToken';
import { IIpnutToken } from './components/inputToken';
import { IMenuToken } from './components/menuToken';
import { INotificationToken } from './components/notificationToken';
import { IPaginationToken } from './components/paginationToken';
import { IPopconfirmToken } from './components/popconfirmToken';
import { IPopoverCardToken } from './components/popoverCardToken';
import { IProgressToken } from './components/progressToken';
import { IRadioToken } from './components/radioToken';
import { IResultToken } from './components/resultToken';
import { ISelectToken } from './components/selectToken';
import { ISkeletonToken } from './components/skeletonToken';
import { ISliderToken } from './components/sliderToken';
import { ISpinToken } from './components/spinToken';
import { IStepsToken } from './components/stepsToken';
import { ISwitchToken } from './components/switchToken';
import { ITableToken } from './components/tableToken';
import { ITabsToken } from './components/tabsToken';
import { ITagToken } from './components/tagToken';
import { ITimePickerToken } from './components/timepickerToken';
import { ITooltipToken } from './components/tooltipToken';
import { ITreeSelectToken } from './components/treeSelectToken';
import { ITreeToken } from './components/treeToken';
import { ITypographyToken } from './components/typographyToken';
import { IUploadToken } from './components/uploadToken';
import { ICollapseToken } from './components/collapseToken';
import { IScrollViewToken } from './components/scrollViewToken';
import { IOpacity } from './opacity';
import { IShadows } from './shadows';
import { ISize } from './size';
import { ISpacing } from './spacing';
import { ITransition } from './transition';
import { ITypography } from './typography';
import { IZIndex } from './zIndex';

export interface IComponents {
  Alert: IAlertToken;
  Badge: IBadgeToken;
  BaseMenu: IBaseMenuToken;
  Breadcrumbs: IBreadcrumbsToken;
  Button: IButtonToken;
  Calendar: ICalendarToken;
  Card: ICardToken;
  Carousel: ICarouselToken;
  Cascader: ICascaderToken;
  Checkbox: ICheckboxToken;
  DatePicker: IDatePickerToken;
  Dialog: IDialogToken;
  Dropdown: IDropdownToken;
  Form: IFormToken;
  Guide: IGuideToken;
  Input: IIpnutToken;
  ImgCropper: IImgCropperToken;
  ImgPreview: IImgPreviewToken;
  InputNumber: IInputNumberToken;
  Menu: IMenuToken;
  Notification: INotificationToken;
  Pagination: IPaginationToken;
  Popconfirm: IPopconfirmToken;
  PopoverCard: IPopoverCardToken;
  Progress: IProgressToken;
  Radio: IRadioToken;
  Result: IResultToken;
  ScrollView: IScrollViewToken;
  Select: ISelectToken;
  Skeleton: ISkeletonToken;
  Spin: ISpinToken;
  Steps: IStepsToken;
  Switch: ISwitchToken;
  Slider: ISliderToken;
  Table: ITableToken;
  Tabs: ITabsToken;
  Tag: ITagToken;
  Tooltip: ITooltipToken;
  Tree: ITreeToken;
  TreeSelect: ITreeSelectToken;
  Typography: ITypographyToken;
  Upload: IUploadToken;
  TimePicker: ITimePickerToken;
  Img: IImgToken;
  Collapse: ICollapseToken;
}

export interface IThemeWithoutComponents {
  themeName: string;
  prefix: string;
  breakpoints: IBreakpoints;
  colors: IColors;
  opacity: IOpacity;
  shadows: IShadows;
  size: ISize;
  spacing: ISpacing;
  transition: ITransition;
  typography: ITypography;
  zIndex: IZIndex;
}

export interface ITheme extends IThemeWithoutComponents {
  components: IComponents;
}
